language: android
jdk: oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses: 
    - android-sdk-license-c81a61d9
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
    
before_install:
 - chmod +x gradlew
 
notifications:
  email: false
  
  
