language: android
jdk: oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - build-tools-2.14.1
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses: 
    - android-sdk-license-c81a61d9
 
before_install:
 - chmod +x gradlew
 
notifications:
  email: false
  
  
